CREATE TABLE CUSTOMER
(
    ID         VARCHAR(255) NOT NULL,
    FIRST_NAME varchar(30)  NOT NULL,
    LAST_NAME  varchar(30),
    EMAIL      VARCHAR(40),
    PHONE      VARCHAR(12),
    PRIMARY KEY (ID)
);

CREATE TABLE TRANSACTION
(
    ID               VARCHAR(255) NOT NULL PRIMARY KEY,
    AMOUNT           NUMBER       NOT NULL,
    CUSTOMER_ID      VARCHAR,
    TRANSACTION_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);

